using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Persists a procedural sprite generated by <see cref="LobbyVisuals"/> across
/// scene saves / Play mode / domain reloads. Without this, the runtime-created
/// Sprite that LobbyLayoutBuilder assigns to <see cref="Image.sprite"/> evaporates
/// after the next domain reload (the Sprite is not a project asset, just a
/// reference into the static <see cref="LobbyVisuals"/> cache, which is empty
/// after a reload). Affected Images then render as plain white rectangles.
///
/// This component stores the parameters needed to recreate the sprite and
/// re-applies it in <see cref="OnEnable"/>. Marked <see cref="ExecuteAlways"/>
/// so it also fires in edit mode — the sprite is rebuilt as soon as the scene
/// finishes loading, which means the canvas looks correct in the editor too.
/// </summary>
[ExecuteAlways]
[RequireComponent(typeof(Image))]
[DisallowMultipleComponent]
public class LobbyProceduralSprite : MonoBehaviour
{
    public enum SpriteKind
    {
        RoundedRect,
        VerticalGradient,
        RadialGlow,
        Vignette,
        SubtlePattern,
        WhitePixel
    }

    [SerializeField] private SpriteKind kind = SpriteKind.RoundedRect;

    [Header("Rounded Rect")]
    [SerializeField, Range(2, 96)] private int cornerRadius = 10;
    [SerializeField, Range(0, 16)] private int borderThickness = 3;
    [SerializeField] private Color fill = Color.white;
    [SerializeField] private Color borderColor = Color.black;

    [Header("Gradient / Glow / Pattern")]
    [SerializeField] private Color colorPrimary = Color.white;
    [SerializeField] private Color colorSecondary = Color.black;
    [SerializeField, Range(8, 1024)] private int size = 256;

    private void OnEnable()
    {
        Refresh();
    }

    /// <summary>
    /// Apply (or re-apply) the sprite. Safe to call any time.
    /// </summary>
    public void Refresh()
    {
        var img = GetComponent<Image>();
        if (img == null) return;

        switch (kind)
        {
            case SpriteKind.RoundedRect:
                img.sprite = LobbyVisuals.GetRoundedRect(cornerRadius, borderThickness, fill, borderColor);
                if (img.type != Image.Type.Sliced) img.type = Image.Type.Sliced;
                break;
            case SpriteKind.VerticalGradient:
                img.sprite = LobbyVisuals.GetVerticalGradient(colorPrimary, colorSecondary, size);
                break;
            case SpriteKind.RadialGlow:
                img.sprite = LobbyVisuals.GetRadialGlow(colorPrimary, size);
                break;
            case SpriteKind.Vignette:
                img.sprite = LobbyVisuals.GetVignette(colorPrimary, size);
                break;
            case SpriteKind.SubtlePattern:
                img.sprite = LobbyVisuals.GetSubtlePattern(colorPrimary, size);
                break;
            case SpriteKind.WhitePixel:
                img.sprite = LobbyVisuals.GetWhitePixel();
                break;
        }
    }

    [ContextMenu("Refresh Sprite")]
    private void RefreshContextMenu() => Refresh();

    // ─── Setters used by LobbyLayoutBuilder when building or patching ──

    public void SetRoundedRect(int corner, int border, Color fillColor, Color borderCol)
    {
        kind = SpriteKind.RoundedRect;
        cornerRadius = Mathf.Max(2, corner);
        borderThickness = Mathf.Max(0, border);
        fill = fillColor;
        borderColor = borderCol;
        Refresh();
    }

    public void SetVerticalGradient(Color top, Color bottom, int height = 256)
    {
        kind = SpriteKind.VerticalGradient;
        colorPrimary = top;
        colorSecondary = bottom;
        size = Mathf.Max(8, height);
        Refresh();
    }

    public void SetRadialGlow(Color center, int sizePx = 256)
    {
        kind = SpriteKind.RadialGlow;
        colorPrimary = center;
        size = Mathf.Max(8, sizePx);
        Refresh();
    }

    public void SetVignette(Color edge, int sizePx = 512)
    {
        kind = SpriteKind.Vignette;
        colorPrimary = edge;
        size = Mathf.Max(8, sizePx);
        Refresh();
    }

    public void SetSubtlePattern(Color line, int sizePx = 32)
    {
        kind = SpriteKind.SubtlePattern;
        colorPrimary = line;
        size = Mathf.Max(8, sizePx);
        Refresh();
    }
}
