using TMPro;
using UnityEngine;
using UnityEngine.UI;

/// <summary>
/// Builds the polished lobby layout procedurally at runtime.
///
/// Three-column composition (Players | Character | Team/Mode/Ready) sits over a
/// gradient backdrop with a subtle diagonal pattern and a corner vignette.
/// All visual primitives are generated by <see cref="LobbyVisuals"/>, so this
/// component does not depend on imported sprites.
///
/// Buttons get a rounded sliced sprite, a vertical gradient overlay, a soft drop
/// shadow, an outline, and a <see cref="UIButtonHoverEffect"/> for hover/press
/// polish and persistent selected states. Arrow buttons in the character carousel
/// are circular with the same hover behaviour.
/// </summary>
public class LobbyLayoutBuilder : MonoBehaviour
{
    [Header("References")]
    [SerializeField] private LobbyUI lobbyUI;
    [SerializeField] private CharacterPreviewUI characterPreview;

    [Header("Prefab")]
    [SerializeField] private GameObject playerEntryPrefab;

    [Header("Fonts")]
    [SerializeField] private TMP_FontAsset font;

    // ─── Palette ──────────────────────────────────────────────────────
    private static readonly Color BgDeep = new Color(0.04f, 0.05f, 0.08f, 1f);
    private static readonly Color BgMid = new Color(0.07f, 0.08f, 0.12f, 1f);
    private static readonly Color PanelFill = new Color(0.10f, 0.11f, 0.16f, 0.92f);
    private static readonly Color PanelInner = new Color(0.13f, 0.14f, 0.20f, 0.85f);
    private static readonly Color PanelBorder = new Color(0.30f, 0.55f, 0.95f, 0.55f);
    private static readonly Color AccentCyan = new Color(0.40f, 0.80f, 1.00f, 1f);
    private static readonly Color AccentSoft = new Color(0.85f, 0.90f, 1.00f, 1f);
    private static readonly Color TextHeader = new Color(0.95f, 0.96f, 1.00f, 1f);
    private static readonly Color TextBody = new Color(0.74f, 0.76f, 0.84f, 1f);
    private static readonly Color TextDim = new Color(0.55f, 0.58f, 0.66f, 1f);

    private static readonly Color RebelsCol = new Color(0.92f, 0.32f, 0.34f, 1f);
    private static readonly Color AICol = new Color(0.32f, 0.55f, 0.95f, 1f);
    private static readonly Color NoneCol = new Color(0.50f, 0.50f, 0.58f, 1f);
    private static readonly Color FFACol = new Color(0.95f, 0.65f, 0.22f, 1f);
    private static readonly Color TDMCol = new Color(0.22f, 0.78f, 0.55f, 1f);
    private static readonly Color ReadyCol = new Color(0.24f, 0.78f, 0.36f, 1f);

    // Built UI references (exposed for LobbyUI wiring)
    private Transform playerListContent;
    private Button rebelsButton, aiButton, noTeamButton;
    private Button ffaButton, tdmButton;
    private Button readyButton;
    private TMP_Text readyButtonText;
    private Image readyButtonImage;
    private TMP_Text statusText;
    private TMP_Text gameModeText;
    private GameObject lobbyContentRoot;
    private TMP_Text characterTaglineText;

    private void Awake()
    {
        BuildLayout();
        WireReferences();
    }

    // ─── Top-level layout ──────────────────────────────────────────────

    private void BuildLayout()
    {
        Canvas canvas = GetComponentInParent<Canvas>();
        if (canvas == null)
        {
            var canvasObj = new GameObject("LobbyCanvas");
            canvas = canvasObj.AddComponent<Canvas>();
            canvas.renderMode = RenderMode.ScreenSpaceOverlay;
            canvas.sortingOrder = 10;
            var scaler = canvasObj.AddComponent<CanvasScaler>();
            scaler.uiScaleMode = CanvasScaler.ScaleMode.ScaleWithScreenSize;
            scaler.referenceResolution = new Vector2(1920, 1080);
            scaler.matchWidthOrHeight = 0.5f;
            canvasObj.AddComponent<GraphicRaycaster>();
            transform.SetParent(canvasObj.transform, false);
        }

        // Layered background sits behind the lobby content but inside the same canvas.
        BuildBackground(transform);

        lobbyContentRoot = CreateAnchoredPanel("LobbyContent", transform, Vector2.zero, Vector2.one, Color.clear);

        BuildLeftPanel(lobbyContentRoot.transform);
        BuildCenterPanel(lobbyContentRoot.transform);
        BuildRightPanel(lobbyContentRoot.transform);
        BuildStatusBar(lobbyContentRoot.transform);

        BuildTopTitle(lobbyContentRoot.transform);
    }

    private static void BuildBackground(Transform parent)
    {
        // Bottom: vertical gradient from BgDeep (top) to BgMid (bottom)
        var gradient = CreateAnchoredPanel("BG_Gradient", parent, Vector2.zero, Vector2.one, Color.white);
        var gradImg = gradient.GetComponent<Image>();
        gradImg.sprite = LobbyVisuals.GetVerticalGradient(BgDeep, BgMid);
        gradImg.type = Image.Type.Simple;
        gradImg.raycastTarget = false;

        // Subtle diagonal scan-line pattern (low alpha, tiled)
        var pattern = CreateAnchoredPanel("BG_Pattern", parent, Vector2.zero, Vector2.one, Color.white);
        var patImg = pattern.GetComponent<Image>();
        patImg.sprite = LobbyVisuals.GetSubtlePattern(new Color(0.55f, 0.7f, 1f, 1f));
        patImg.type = Image.Type.Tiled;
        patImg.color = new Color(1f, 1f, 1f, 0.10f);
        patImg.raycastTarget = false;

        // Corner vignette
        var vignette = CreateAnchoredPanel("BG_Vignette", parent, Vector2.zero, Vector2.one, Color.white);
        var vigImg = vignette.GetComponent<Image>();
        vigImg.sprite = LobbyVisuals.GetVignette(new Color(0f, 0f, 0f, 1f));
        vigImg.color = new Color(1f, 1f, 1f, 0.65f);
        vigImg.raycastTarget = false;
    }

    private void BuildTopTitle(Transform parent)
    {
        var bar = CreateAnchoredPanel("TitleBar", parent,
            new Vector2(0f, 0.945f), new Vector2(1f, 1f), Color.clear);

        var titleObj = CreateText("LobbyTitle", bar.transform, "MULTIPLAYER LOBBY", 30, AccentCyan,
            new Vector2(0f, 0f), new Vector2(1f, 1f), TextAlignmentOptions.Center,
            new Vector2(0, 0), new Vector2(0, 0));
        titleObj.fontStyle = FontStyles.Bold | FontStyles.UpperCase;
        var titleOutline = titleObj.gameObject.AddComponent<Outline>();
        titleOutline.effectColor = new Color(0.12f, 0.45f, 0.85f, 0.7f);
        titleOutline.effectDistance = new Vector2(1.2f, -1.2f);

        // Thin accent strip under the title
        var strip = CreateAnchoredPanel("TitleStrip", bar.transform,
            new Vector2(0.32f, 0.05f), new Vector2(0.68f, 0.07f), Color.white);
        var stripImg = strip.GetComponent<Image>();
        stripImg.sprite = LobbyVisuals.GetVerticalGradient(new Color(0f, 0f, 0f, 0f), AccentCyan);
        stripImg.color = new Color(1f, 1f, 1f, 0.7f);
    }

    // ─── LEFT PANEL: Player List ──────────────────────────────────────

    private void BuildLeftPanel(Transform parent)
    {
        var panel = CreateRoundedPanel("LeftPanel", parent,
            new Vector2(0.013f, 0.075f),
            new Vector2(0.245f, 0.94f),
            PanelFill, PanelBorder, cornerRadius: 14, borderThickness: 2);

        // Header
        CreateText("PlayerListHeader", panel.transform, "PLAYERS", 22, TextHeader,
            new Vector2(0f, 0.92f), new Vector2(1f, 0.98f), TextAlignmentOptions.Center,
            new Vector2(10, 0), new Vector2(-10, 0)).fontStyle = FontStyles.Bold | FontStyles.UpperCase;

        // Accent separator
        var sep = CreateAnchoredPanel("Sep", panel.transform,
            new Vector2(0.10f, 0.905f), new Vector2(0.90f, 0.915f), Color.white);
        var sepImg = sep.GetComponent<Image>();
        sepImg.sprite = LobbyVisuals.GetVerticalGradient(new Color(0f, 0f, 0f, 0f), AccentCyan);
        sepImg.color = new Color(1f, 1f, 1f, 0.6f);

        // Scrollable list
        var scrollArea = CreateAnchoredPanel("PlayerScrollArea", panel.transform,
            new Vector2(0.02f, 0.02f), new Vector2(0.98f, 0.895f), Color.clear);

        var scrollRect = scrollArea.AddComponent<ScrollRect>();
        scrollRect.horizontal = false;
        scrollRect.verticalScrollbarVisibility = ScrollRect.ScrollbarVisibility.AutoHide;

        var viewport = CreateAnchoredPanel("Viewport", scrollArea.transform, Vector2.zero, Vector2.one, Color.clear);
        viewport.AddComponent<RectMask2D>();

        var content = new GameObject("Content", typeof(RectTransform));
        content.transform.SetParent(viewport.transform, false);
        var contentRT = (RectTransform)content.transform;
        contentRT.anchorMin = new Vector2(0, 1);
        contentRT.anchorMax = new Vector2(1, 1);
        contentRT.pivot = new Vector2(0.5f, 1);
        contentRT.offsetMin = new Vector2(6, 0);
        contentRT.offsetMax = new Vector2(-6, 0);

        var vlg = content.AddComponent<VerticalLayoutGroup>();
        vlg.spacing = 6;
        vlg.padding = new RectOffset(4, 4, 6, 6);
        vlg.childForceExpandWidth = true;
        vlg.childForceExpandHeight = false;
        vlg.childControlWidth = true;
        vlg.childControlHeight = true;

        var csf = content.AddComponent<ContentSizeFitter>();
        csf.verticalFit = ContentSizeFitter.FitMode.PreferredSize;

        scrollRect.content = contentRT;
        scrollRect.viewport = (RectTransform)viewport.transform;

        playerListContent = content.transform;
    }

    // ─── CENTER PANEL: Character Preview ──────────────────────────────

    private void BuildCenterPanel(Transform parent)
    {
        var panel = CreateAnchoredPanel("CenterPanel", parent,
            new Vector2(0.255f, 0.075f),
            new Vector2(0.745f, 0.94f),
            Color.clear);

        // Soft radial accent glow behind the preview frame, tinted to follow the character.
        var glow = CreateAnchoredPanel("PreviewGlow", panel.transform,
            new Vector2(-0.05f, 0.0f), new Vector2(1.05f, 0.95f), Color.white);
        var glowImg = glow.GetComponent<Image>();
        glowImg.sprite = LobbyVisuals.GetRadialGlow(AccentCyan);
        glowImg.color = new Color(1f, 1f, 1f, 0.55f);
        glowImg.raycastTarget = false;

        // Rounded panel "frame" containing the RawImage
        var frame = CreateRoundedPanel("PreviewFrame", panel.transform,
            new Vector2(0.06f, 0.10f), new Vector2(0.94f, 0.86f),
            PanelInner, PanelBorder, cornerRadius: 18, borderThickness: 2);

        // Character preview RawImage inside the frame
        var previewObj = new GameObject("CharacterPreviewImage", typeof(RectTransform));
        previewObj.transform.SetParent(frame.transform, false);
        var previewRT = (RectTransform)previewObj.transform;
        previewRT.anchorMin = new Vector2(0.04f, 0.04f);
        previewRT.anchorMax = new Vector2(0.96f, 0.96f);
        previewRT.offsetMin = Vector2.zero;
        previewRT.offsetMax = Vector2.zero;
        var previewImage = previewObj.AddComponent<RawImage>();
        previewImage.color = Color.white;
        previewImage.raycastTarget = false;

        // Title above the frame: character display name
        var charNameText = CreateText("CharacterName", panel.transform, "Select Character", 36, AccentCyan,
            new Vector2(0.10f, 0.875f), new Vector2(0.90f, 0.96f), TextAlignmentOptions.Center);
        charNameText.fontStyle = FontStyles.Bold;
        var nameOutline = charNameText.gameObject.AddComponent<Outline>();
        nameOutline.effectColor = new Color(0.10f, 0.40f, 0.80f, 0.7f);
        nameOutline.effectDistance = new Vector2(1.2f, -1.2f);

        // Tagline below the name
        characterTaglineText = CreateText("CharacterTagline", panel.transform, "", 16, TextBody,
            new Vector2(0.10f, 0.83f), new Vector2(0.90f, 0.88f), TextAlignmentOptions.Center);
        characterTaglineText.fontStyle = FontStyles.Italic;

        // Circular arrow buttons
        var leftArrow = CreateCircularArrowButton("LeftArrow", panel.transform, "<",
            new Vector2(-0.02f, 0.40f), new Vector2(0.10f, 0.60f));
        var rightArrow = CreateCircularArrowButton("RightArrow", panel.transform, ">",
            new Vector2(0.90f, 0.40f), new Vector2(1.02f, 0.60f));

        if (characterPreview != null)
        {
            characterPreview.SetPreviewImage(previewImage);
            characterPreview.SetArrowButtons(leftArrow, rightArrow);
            characterPreview.SetCharacterNameText(charNameText);
            characterPreview.SetCharacterTaglineText(characterTaglineText);

            // Retint the radial glow with the active character's accent color
            characterPreview.OnDefinitionChanged += def =>
            {
                if (def == null) return;
                glowImg.color = new Color(def.accentColor.r, def.accentColor.g, def.accentColor.b, 0.55f);
                charNameText.color = def.accentColor;
                Color outlineCol = def.accentColor * 0.6f;
                outlineCol.a = 0.7f;
                nameOutline.effectColor = outlineCol;
            };
        }
    }

    // ─── RIGHT PANEL: Team, Mode, Ready ───────────────────────────────

    private void BuildRightPanel(Transform parent)
    {
        var panel = CreateRoundedPanel("RightPanel", parent,
            new Vector2(0.755f, 0.075f),
            new Vector2(0.987f, 0.94f),
            PanelFill, PanelBorder, cornerRadius: 14, borderThickness: 2);

        float yTop = 0.96f;
        float headerHeight = 0.045f;
        float sectionGap = 0.025f;
        float btnH = 0.072f;
        float btnGap = 0.016f;

        // ─── TEAM ───
        CreateSectionHeader(panel.transform, "TEAM", yTop - headerHeight, yTop);
        yTop -= headerHeight + sectionGap;

        rebelsButton = CreateLobbyButton("RebelsBtn", panel.transform, "REBELS", "✦",
            new Vector2(0.08f, yTop - btnH), new Vector2(0.92f, yTop), RebelsCol);
        yTop -= btnH + btnGap;

        aiButton = CreateLobbyButton("AIBtn", panel.transform, "AI", "◆",
            new Vector2(0.08f, yTop - btnH), new Vector2(0.92f, yTop), AICol);
        yTop -= btnH + btnGap;

        noTeamButton = CreateLobbyButton("NoTeamBtn", panel.transform, "NO TEAM", "—",
            new Vector2(0.08f, yTop - btnH), new Vector2(0.92f, yTop), NoneCol);
        yTop -= btnH + sectionGap * 2;

        // ─── GAME MODE ───
        CreateSectionHeader(panel.transform, "GAME MODE", yTop - headerHeight, yTop);
        yTop -= headerHeight + sectionGap;

        ffaButton = CreateLobbyButton("FFABtn", panel.transform, "FREE FOR ALL", "●",
            new Vector2(0.08f, yTop - btnH), new Vector2(0.92f, yTop), FFACol);
        yTop -= btnH + btnGap;

        tdmButton = CreateLobbyButton("TDMBtn", panel.transform, "TEAM DEATHMATCH", "▲",
            new Vector2(0.08f, yTop - btnH), new Vector2(0.92f, yTop), TDMCol);
        yTop -= btnH + sectionGap;

        // ─── Vote tally ───
        gameModeText = CreateText("GameModeVote", panel.transform, "", 15, TextDim,
            new Vector2(0.06f, yTop - 0.05f), new Vector2(0.94f, yTop), TextAlignmentOptions.Center);
        gameModeText.fontStyle = FontStyles.Italic;

        // ─── READY (large, bottom) ───
        float readyH = 0.10f;
        float readyY = 0.035f;
        readyButton = CreateLobbyButton("ReadyBtn", panel.transform, "READY UP", "✓",
            new Vector2(0.06f, readyY), new Vector2(0.94f, readyY + readyH), ReadyCol);
        readyButtonText = readyButton.GetComponentInChildren<TMP_Text>();
        readyButtonImage = readyButton.GetComponent<Image>();

        // Make the Ready button pulse when armed (the SetSelected toggle on its hover effect drives this)
        var readyHover = readyButton.GetComponent<UIButtonHoverEffect>();
        if (readyHover != null)
            readyHover.EnableSelectedPulse(speed: 2.6f, amplitude: 0.45f);
    }

    private void CreateSectionHeader(Transform parent, string text, float yMin, float yMax)
    {
        var header = CreateText($"Header_{text}", parent, text, 19, TextHeader,
            new Vector2(0f, yMin), new Vector2(1f, yMax), TextAlignmentOptions.Center,
            new Vector2(15, 0), new Vector2(-15, 0));
        header.fontStyle = FontStyles.Bold | FontStyles.UpperCase;
        header.characterSpacing = 6f;

        // Tiny accent bar under the header
        var bar = CreateAnchoredPanel($"HeaderBar_{text}", parent,
            new Vector2(0.30f, yMin - 0.005f), new Vector2(0.70f, yMin - 0.001f), Color.white);
        var img = bar.GetComponent<Image>();
        img.sprite = LobbyVisuals.GetVerticalGradient(new Color(0f, 0f, 0f, 0f), AccentCyan);
        img.color = new Color(1f, 1f, 1f, 0.65f);
    }

    // ─── STATUS BAR ────────────────────────────────────────────────────

    private void BuildStatusBar(Transform parent)
    {
        var bar = CreateRoundedPanel("StatusBar", parent,
            new Vector2(0.013f, 0.012f), new Vector2(0.987f, 0.062f),
            new Color(0.04f, 0.05f, 0.08f, 0.95f), PanelBorder, cornerRadius: 10, borderThickness: 1);

        statusText = CreateText("StatusText", bar.transform, "Connecting...", 17, TextBody,
            new Vector2(0f, 0f), new Vector2(0.55f, 1f), TextAlignmentOptions.MidlineLeft,
            new Vector2(24, 0), new Vector2(-12, 0));

        // gameModeText already lives in the right panel; the status bar's right side
        // mirrors the connection / vote summary at a glance.
        var rightStatus = CreateText("StatusRight", bar.transform, "", 15, TextDim,
            new Vector2(0.55f, 0f), new Vector2(1f, 1f), TextAlignmentOptions.MidlineRight,
            new Vector2(12, 0), new Vector2(-24, 0));
        rightStatus.fontStyle = FontStyles.Italic;
        // We reuse statusText; rightStatus is purely decorative and shows a tip.
        rightStatus.text = "Pick a team & game mode, then ready up";
    }

    // ─── WIRING ────────────────────────────────────────────────────────

    private void WireReferences()
    {
        if (lobbyUI == null) return;

        lobbyUI.SetupLayoutReferences(
            playerListContent: playerListContent,
            playerEntryPrefab: playerEntryPrefab,
            rebelsButton: rebelsButton,
            aiButton: aiButton,
            noTeamButton: noTeamButton,
            ffaButton: ffaButton,
            tdmButton: tdmButton,
            characterPreview: characterPreview,
            readyButton: readyButton,
            readyButtonText: readyButtonText,
            readyButtonImage: readyButtonImage,
            statusText: statusText,
            gameModeText: gameModeText,
            lobbyContentRoot: lobbyContentRoot
        );
    }

    // ─── UI Factory Helpers ────────────────────────────────────────────

    private static GameObject CreateAnchoredPanel(string name, Transform parent, Vector2 anchorMin, Vector2 anchorMax, Color color)
    {
        var obj = new GameObject(name, typeof(RectTransform));
        obj.transform.SetParent(parent, false);
        var rt = (RectTransform)obj.transform;
        rt.anchorMin = anchorMin;
        rt.anchorMax = anchorMax;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;
        if (color.a > 0)
        {
            var img = obj.AddComponent<Image>();
            img.color = color;
        }
        return obj;
    }

    /// <summary>
    /// Rounded panel with a sliced fill and a 1-2 px accent border. Includes a soft drop shadow.
    /// </summary>
    private static GameObject CreateRoundedPanel(string name, Transform parent, Vector2 anchorMin, Vector2 anchorMax,
        Color fill, Color borderColor, int cornerRadius = 14, int borderThickness = 2)
    {
        var obj = new GameObject(name, typeof(RectTransform));
        obj.transform.SetParent(parent, false);
        var rt = (RectTransform)obj.transform;
        rt.anchorMin = anchorMin;
        rt.anchorMax = anchorMax;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;

        var img = obj.AddComponent<Image>();
        img.sprite = LobbyVisuals.GetRoundedRect(cornerRadius, borderThickness, fill, borderColor);
        img.type = Image.Type.Sliced;
        img.pixelsPerUnitMultiplier = 1f;

        var shadow = obj.AddComponent<Shadow>();
        shadow.effectColor = new Color(0f, 0f, 0f, 0.55f);
        shadow.effectDistance = new Vector2(0f, -3f);
        return obj;
    }

    private TMP_Text CreateText(string name, Transform parent, string text, int fontSize, Color color,
        Vector2 anchorMin, Vector2 anchorMax, TextAlignmentOptions alignment = TextAlignmentOptions.Center,
        Vector2? offsetMin = null, Vector2? offsetMax = null)
    {
        var obj = new GameObject(name, typeof(RectTransform));
        obj.transform.SetParent(parent, false);
        var rt = (RectTransform)obj.transform;
        rt.anchorMin = anchorMin;
        rt.anchorMax = anchorMax;
        rt.offsetMin = offsetMin ?? Vector2.zero;
        rt.offsetMax = offsetMax ?? Vector2.zero;

        var tmp = obj.AddComponent<TextMeshProUGUI>();
        tmp.text = text;
        tmp.fontSize = fontSize;
        tmp.color = color;
        tmp.alignment = alignment;
        tmp.fontStyle = FontStyles.Bold;
        if (font != null) tmp.font = font;
        tmp.raycastTarget = false;
        return tmp;
    }

    /// <summary>
    /// Rounded button with: gradient overlay, drop shadow, accent outline, soft inner glow,
    /// optional left-side icon glyph, and a <see cref="UIButtonHoverEffect"/> for polish.
    /// </summary>
    private Button CreateLobbyButton(string name, Transform parent, string label, string iconGlyph,
        Vector2 anchorMin, Vector2 anchorMax, Color tint)
    {
        // Root button image (rounded sliced fill)
        var obj = new GameObject(name, typeof(RectTransform));
        obj.transform.SetParent(parent, false);
        var rt = (RectTransform)obj.transform;
        rt.anchorMin = anchorMin;
        rt.anchorMax = anchorMax;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;

        Color baseFill = Color.Lerp(new Color(0.10f, 0.12f, 0.16f, 1f), tint, 0.55f);
        Color borderCol = tint;
        var img = obj.AddComponent<Image>();
        img.sprite = LobbyVisuals.GetRoundedRect(cornerRadius: 12, borderThickness: 2, baseFill, borderCol);
        img.type = Image.Type.Sliced;
        img.pixelsPerUnitMultiplier = 1f;

        var shadow = obj.AddComponent<Shadow>();
        shadow.effectColor = new Color(0f, 0f, 0f, 0.55f);
        shadow.effectDistance = new Vector2(0f, -2.5f);

        var outline = obj.AddComponent<Outline>();
        Color outlineCol = tint;
        outlineCol.a = 0f; // hover effect drives alpha
        outline.effectColor = outlineCol;
        outline.effectDistance = new Vector2(1.4f, -1.4f);

        var btn = obj.AddComponent<Button>();
        var colors = btn.colors;
        Color top = baseFill * 1.15f;
        Color bot = baseFill * 0.75f;
        colors.normalColor = baseFill;
        colors.highlightedColor = top;
        colors.pressedColor = bot;
        colors.selectedColor = baseFill;
        colors.fadeDuration = 0.10f;
        btn.colors = colors;
        btn.targetGraphic = img;

        // Vertical gradient overlay (top brighter, bottom darker) for depth
        var grad = new GameObject("Gradient", typeof(RectTransform));
        grad.transform.SetParent(obj.transform, false);
        var gradRT = (RectTransform)grad.transform;
        gradRT.anchorMin = new Vector2(0f, 0f);
        gradRT.anchorMax = new Vector2(1f, 1f);
        gradRT.offsetMin = new Vector2(2, 2);
        gradRT.offsetMax = new Vector2(-2, -2);
        var gradImg = grad.AddComponent<Image>();
        gradImg.sprite = LobbyVisuals.GetVerticalGradient(new Color(1f, 1f, 1f, 0.18f), new Color(0f, 0f, 0f, 0.18f));
        gradImg.color = Color.white;
        gradImg.raycastTarget = false;

        // Soft inner glow (driven by hover effect)
        var glow = new GameObject("InnerGlow", typeof(RectTransform));
        glow.transform.SetParent(obj.transform, false);
        var glowRT = (RectTransform)glow.transform;
        glowRT.anchorMin = new Vector2(-0.05f, -0.15f);
        glowRT.anchorMax = new Vector2(1.05f, 1.15f);
        glowRT.offsetMin = Vector2.zero;
        glowRT.offsetMax = Vector2.zero;
        var glowImg = glow.AddComponent<Image>();
        glowImg.sprite = LobbyVisuals.GetRadialGlow(tint);
        glowImg.color = new Color(1f, 1f, 1f, 0f); // hover effect drives alpha
        glowImg.raycastTarget = false;
        glow.transform.SetSiblingIndex(0); // behind the gradient/text

        // Icon
        if (!string.IsNullOrEmpty(iconGlyph))
        {
            var icon = CreateText($"{name}_Icon", obj.transform, iconGlyph, 22, Color.white,
                new Vector2(0f, 0f), new Vector2(0.18f, 1f), TextAlignmentOptions.Center);
            icon.fontStyle = FontStyles.Bold;
        }

        // Label (centered, leaving room for icon on the left)
        var labelObj = CreateText($"{name}_Label", obj.transform, label, 17, Color.white,
            new Vector2(0.18f, 0f), new Vector2(0.92f, 1f), TextAlignmentOptions.Center,
            new Vector2(0, 2), new Vector2(0, -2));
        labelObj.fontStyle = FontStyles.Bold | FontStyles.UpperCase;
        labelObj.characterSpacing = 4f;
        var labelOutline = labelObj.gameObject.AddComponent<Outline>();
        labelOutline.effectColor = new Color(0f, 0f, 0f, 0.55f);
        labelOutline.effectDistance = new Vector2(1f, -1f);

        // Check pip on the right (visible when selected — hover effect can show it via the InnerGlow alpha,
        // but we add a dedicated pip the LobbyUI can flip on/off if desired)
        var pip = new GameObject("CheckPip", typeof(RectTransform));
        pip.transform.SetParent(obj.transform, false);
        var pipRT = (RectTransform)pip.transform;
        pipRT.anchorMin = new Vector2(0.88f, 0.25f);
        pipRT.anchorMax = new Vector2(0.97f, 0.75f);
        pipRT.offsetMin = Vector2.zero;
        pipRT.offsetMax = Vector2.zero;
        var pipText = pip.AddComponent<TextMeshProUGUI>();
        pipText.text = "";
        pipText.fontSize = 18;
        pipText.color = Color.white;
        pipText.alignment = TextAlignmentOptions.Center;
        pipText.fontStyle = FontStyles.Bold;
        if (font != null) pipText.font = font;
        pipText.raycastTarget = false;

        // Hover effect with bound outline + glow refs
        var hover = obj.AddComponent<UIButtonHoverEffect>();
        hover.Bind(outline, glowImg);

        return btn;
    }

    /// <summary>
    /// Circular arrow button used by the character carousel. Built on a heavily rounded sliced sprite.
    /// </summary>
    private Button CreateCircularArrowButton(string name, Transform parent, string arrow,
        Vector2 anchorMin, Vector2 anchorMax)
    {
        var obj = new GameObject(name, typeof(RectTransform));
        obj.transform.SetParent(parent, false);
        var rt = (RectTransform)obj.transform;
        rt.anchorMin = anchorMin;
        rt.anchorMax = anchorMax;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;

        Color fill = new Color(0.13f, 0.16f, 0.22f, 0.95f);
        Color border = AccentCyan;
        var img = obj.AddComponent<Image>();
        // Large corner radius approximates a circle when the rect is square-ish.
        img.sprite = LobbyVisuals.GetRoundedRect(cornerRadius: 64, borderThickness: 2, fill, border);
        img.type = Image.Type.Sliced;
        img.pixelsPerUnitMultiplier = 1f;

        var shadow = obj.AddComponent<Shadow>();
        shadow.effectColor = new Color(0f, 0f, 0f, 0.6f);
        shadow.effectDistance = new Vector2(0f, -2f);

        var outline = obj.AddComponent<Outline>();
        Color outlineCol = AccentCyan;
        outlineCol.a = 0f;
        outline.effectColor = outlineCol;
        outline.effectDistance = new Vector2(1.2f, -1.2f);

        var btn = obj.AddComponent<Button>();
        var colors = btn.colors;
        colors.normalColor = fill;
        colors.highlightedColor = fill * 1.3f;
        colors.pressedColor = fill * 0.85f;
        colors.selectedColor = fill;
        btn.colors = colors;
        btn.targetGraphic = img;

        // Soft inner glow
        var glow = new GameObject("InnerGlow", typeof(RectTransform));
        glow.transform.SetParent(obj.transform, false);
        var glowRT = (RectTransform)glow.transform;
        glowRT.anchorMin = new Vector2(-0.10f, -0.10f);
        glowRT.anchorMax = new Vector2(1.10f, 1.10f);
        glowRT.offsetMin = Vector2.zero;
        glowRT.offsetMax = Vector2.zero;
        var glowImg = glow.AddComponent<Image>();
        glowImg.sprite = LobbyVisuals.GetRadialGlow(AccentCyan);
        glowImg.color = new Color(1f, 1f, 1f, 0f);
        glowImg.raycastTarget = false;
        glow.transform.SetSiblingIndex(0);

        var arrowText = CreateText($"{name}_Arrow", obj.transform, arrow, 44, Color.white,
            Vector2.zero, Vector2.one, TextAlignmentOptions.Center);
        arrowText.fontStyle = FontStyles.Bold;
        var arrowOutline = arrowText.gameObject.AddComponent<Outline>();
        arrowOutline.effectColor = new Color(0f, 0f, 0f, 0.55f);
        arrowOutline.effectDistance = new Vector2(1.2f, -1.2f);

        var hover = obj.AddComponent<UIButtonHoverEffect>();
        hover.Bind(outline, glowImg);

        return btn;
    }
}
